# Generated by Django 4.1.3 on 2022-12-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auctionlisting_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='activestatus',
            field=models.BooleanField(default=True),
        ),
    ]
