# Generated by Django 4.1.3 on 2022-12-14 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_watching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watching', to=settings.AUTH_USER_MODEL)),
                ('watched_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_listing', to='auctions.auctionlisting')),
            ],
        ),
    ]
